
name: Docker Image Scan Workflow

on:
  push:
    branches:
      - main

jobs:
  Get_Docker_Images:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAMES: "otel/opentelemetry-collector:0.91.0 dirajan/mongo:v6"
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: install trivy
      run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

    - name: Loop through Docker images
      run: |
        IFS=' ' read -ra IMAGE_ARRAY <<< "$IMAGE_NAMES"
        for IMAGE_NAME in "${IMAGE_ARRAY[@]}"; do
          echo "Processing image: $IMAGE_NAME"
          # Pull Docker image
          docker pull $IMAGE_NAME
          trivy image "$IMAGE_NAME"
          # Get short commit SHA
          SHORT_COMMIT=$(git rev-parse --short ${{ github.sha }})
          IMAGE_NAME_TAGLESS=$(echo $IMAGE_NAME |awk -F ":" '{print $1}')
          echo "Image is $IMAGE_NAME_TAGLESS"
          # Retag Docker image
          docker tag $IMAGE_NAME $IMAGE_NAME_TAGLESS:$SHORT_COMMIT
          IMAGE_SCAN=$(docker image ls|grep $SHORT_COMMIT|awk '{print $1}' |tr "\n" " ")
        done

  job2:
    runs-on: ubuntu-latest
    needs: Get_Docker_Images
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    - name: run kics Scan
      uses: checkmarx/kics-github-action@v1.7.0
      with:
        path: './test/kubernetes.tf'
        output_path: test/
    - name: display kics results
      run: |
        cat test/results.json
    
