# This is a basic workflow to help you get started with Actions

name: test
on: 
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          docker pull dirajan/mongo:v6
          docker run -d -p 3000:3000 dirajan/mongo:v6
      - name: Get short commit SHA
        id: get_commit
        run: echo "::set-output name=short_commit::$(git rev-parse --short ${{ github.sha }})"
      - name: Retag Docker image
        run: |
            docker tag dirajan/mongo:v6 dirajan/mongo:${{ steps.get_commit.outputs.short_commit }}
      - name: Scan Docker image
        run: |
            docker run --rm -v $(pwd):/workdir aquasec/trivy trivy image dirajan/mongo:v6
