name: test

on: 
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: "otel/opentelemetry-collector"
      IMAGE_VERSION: "0.91.0"
  
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Pull Docker image
        run: docker pull $IMAGE:$IMAGE_VERSION

      - name: Get short commit SHA
        id: get_commit
        run: echo "::set-output name=short_commit::$(git rev-parse --short ${{ github.sha }})"

      - name: Retag Docker image
        run: |
            docker tag $IMAGE:$IMAGE_VERSION $IMAGE:${{ steps.get_commit.outputs.short_commit }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: $IMAGE:'${{ steps.get_commit.outputs.short_commit }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
