name: Docker Image Scan Workflow

on:
  push:
    branches:
      - main

jobs:
  scan-docker-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ORIGINAL_TAG:: ["v6", "0.91.0"]
        BASE_IMAGE: ["dirajan/mongo", "otel/opentelemetry-collector"]

   # env:
   #   BASE_IMAGE: "otel/opentelemetry-collector"
   #   ORIGINAL_TAG: "0.91.0"
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Print environment variable values
      run: |
        echo "BASE_IMAGE: ${{metrix.BASE_IMAGE}}"
        echo "ORIGINAL_TAG: ${{metrix.RIGINAL_TAG}}"

    - name: Pull original Docker image
      run: |
        docker pull ${{env.BASE_IMAGE}}:${{env.ORIGINAL_TAG}}

    - name: Get short commit SHA
      id: get_commit
      run: echo "::set-output name=short_commit::$(git rev-parse --short ${{ github.sha }})"

    - name: Retag Docker image
      run: |
        docker tag  ${{env.BASE_IMAGE}}:${{env.ORIGINAL_TAG}} ${{env.BASE_IMAGE}}:${{ steps.get_commit.outputs.short_commit }}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref:  ${{env.BASE_IMAGE}}:${{ steps.get_commit.outputs.short_commit }}
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

