# This is a basic workflow to help you get started with Actions

name: test
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          docker pull dirajan/mongo:v6
          docker run -d -p 3000:3000 dirajan/mongo:v6